### ISSUE TITLE
Library fails on various small keysize inputs

### ISSUE THREAD

**Issue by chrisnojima** [keybase/kbpgp#94]
Passing small values to nbits will cause the library to get stuck in various bad states. given this code:

```
var kbpgp = require('kbpgp');

function go(num) {
    kbpgp.KeyManager.generate({
        asp: new kbpgp.ASP({progress_hook:function(i) {
            console.log('prog: ' + num + JSON.stringify(i));
        }}),
        userid:  'name',
        primary: { nbits: num },
        subkeys: []
    }, function() {
        console.log('done: ' + num);
    });
}

for(var i = 0 ; i < 256 ; ++i) {
    go(i);
}
```

You'll see passing in nbits values 1-3 won't get callbacks ever, 4-33 will be stuck in the 'guess' phase

**Comment by akalin-keybase** [comment]
Coincidentally, I was just looking at this code. A bunch of the prime-generation/testing code probably needs a lower bound to work. I can take a look if I have time.

**Comment by akalin-keybase** [comment]
Okay, dug into this a bit. One problem is that in primegen.iced, prime_search takes a start and a range, and is supposed to find a prime in [start, start + range). We pass nbits as range, which is problematic, as if nbits is small enough, there might be no primes in that range.

I think the right solution would be to pass in nbits instead of range and have the loop look like:

```
  ret = null
  while not ret?
    p = pf.next_weak()
    if p.num_bits() > nbits
      break
    // check p for primality.
```

and this will fail with small probability.

I think this fixes the problem with 4-33, but not 1-3.

Incidentally, what's the deal with test coverage in kbpgp?

**Comment by maxtaco** [comment]
Backing up a few steps, is there any use at all in having keys so small?  Can we just put a lower limit on nbits at like 100, and raise an error if not?

As for test coverage, `make test` has a pretty good suite of tests that all run in the browser.  But obviously the test coverage is far from 100%.

**Comment by chrisnojima** [comment]
I don't care at all about fixing this bug really, just wanted to track it
and note it.
